tasks:
  - init: pip install -r requirements.txt
    command: >
      BASE_URL=$(gp url);
      URL=${BASE_URL/https:\/\//"https://8000-"}/hello;
      printf "${PURPLE}Your URL is: "${URL}" \n${NOCOLOR}";
      python test3.py
ports:
  - port: 8000
    onOpen: ignore
    visibility: public
